// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6P_eg5MkugEiRcLJy5nIqzcFsGY2X0gY',
    appId: '1:569252389470:web:68099a5243467a832c4acf',
    messagingSenderId: '569252389470',
    projectId: 'miro-firebase-3',
    authDomain: 'miro-firebase-3.firebaseapp.com',
    storageBucket: 'miro-firebase-3.appspot.com',
    measurementId: 'G-M404GN22M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAN0OtEAI41Drg1e5jWmEnH1N8OQcILFM',
    appId: '1:569252389470:android:0c15900fab5e12de2c4acf',
    messagingSenderId: '569252389470',
    projectId: 'miro-firebase-3',
    storageBucket: 'miro-firebase-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfQaEVoSd3c46FDHVOfA56lWmgZS1fCPg',
    appId: '1:569252389470:ios:ae4b4b295cbb80422c4acf',
    messagingSenderId: '569252389470',
    projectId: 'miro-firebase-3',
    storageBucket: 'miro-firebase-3.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfQaEVoSd3c46FDHVOfA56lWmgZS1fCPg',
    appId: '1:569252389470:ios:ae4b4b295cbb80422c4acf',
    messagingSenderId: '569252389470',
    projectId: 'miro-firebase-3',
    storageBucket: 'miro-firebase-3.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6P_eg5MkugEiRcLJy5nIqzcFsGY2X0gY',
    appId: '1:569252389470:web:aa23774eac47c9042c4acf',
    messagingSenderId: '569252389470',
    projectId: 'miro-firebase-3',
    authDomain: 'miro-firebase-3.firebaseapp.com',
    storageBucket: 'miro-firebase-3.appspot.com',
    measurementId: 'G-QC8CYPSEWC',
  );
}
